---
location_dropdown:
  label: Location
  dropdown_list:
    - 
      label: Philadelphia, PA
      value: philadelphia
    - 
      label: Seattle, WA
      value: seattle
    - 
      label: Los Angeles, CA
      value: los_angeles
    - 
      label: Chicago, IL
      value: chicago
    - 
      label: Austin, TX
      value: austin
    - 
      label: Atlanta, GA
      value: atlanta
    - 
      label: Unknown
      value: unknown
  first_item: philadelphia
  dropdown_id: location_dropdown

building_use_type_dropdown:
  label: Building Use Type
  dropdown_list:
    - 
      label: Office
      value: office
    - 
      label: Multi-family
      value: multifamily
    - 
      label: Single Family Home
      value: sfh
    - 
      label: Education
      value: education
    - 
      label: Healthcare
      value: healthcare
  first_item: office
  dropdown_id: building_use_type_dropdown

str_horiz_grav_sys_dropdown:
  label: Primary Horizontal Gravity System
  dropdown_list:
    - 
      label: "Concrete: Non-PT Framing"
      value: conc_non_pt
    - 
      label: "Steel: Frame + Concrete on Metal Deck"
      value: steel_w_metal_deck
    - 
      label: "Wood: Engineered Panels"
      value: clt
  first_item: conc_non_pt
  dropdown_id: str_horiz_grav_sys_dropdown

str_vert_grav_sys_dropdown:
  label: Primary Vertical Gravity System
  dropdown_list:
    - 
      label: "Concrete: CIP"
      value: conc_cip
    - 
      label: "Steel: Columns"
      value: steel_col
    - 
      label: "Wood: Mass Timber"
      value: glt
  first_item: conc_cip
  dropdown_id: str_vert_grav_sys_dropdown

str_lat_sys_dropdown:
  label: Primary Lateral System
  dropdown_list:
    - 
      label: "Concrete: Shear Walls"
      value: conc_sw
    - 
      label: "Steel: Braced Frames"
      value: steel_col
    - 
      label: "Wood: Shear Panels"
      value: wood_sw
  first_item: conc_sw
  dropdown_id: str_lat_sys_dropdown

cladding_type_dropdown:
  label: Cladding Type
  dropdown_list:
    - 
      label: "Curtainwall"
      value: curtainwall
    - 
      label: "Wood rainscreen"
      value: wood_rainscreen
  first_item: curtainwall
  dropdown_id: cladding_type_dropdown

roofing_type_dropdown:
  label: Roofing Type
  dropdown_list:
    - 
      label: "Roof Option 1"
      value: roof_1
    - 
      label: "Roof Option 2"
      value: roof_2
  first_item: roof_1
  dropdown_id: roofing_type_dropdown

wwr_dropdown:
  label: Window-to-wall Ratio
  dropdown_list:
    - 
      label: "25%"
      value: 0.25
    - 
      label: "50%"
      value: 0.5
    - 
      label: "75%"
      value: 0.75
  first_item: 0.25
  dropdown_id: wwr_dropdown


scope_dropdown:
  label: Categorization
  dropdown_list:
    - 
      label: Life Cycle Stage
      value: Life Cycle Stage
    - 
      label: Revit Building Element
      value: Revit building element
    - 
      label: Tally Entry Division
      value: Tally Entry Division
    - 
      label: Revit Category
      value: Revit category
  first_item: Life Cycle Stage
  dropdown_id: scope_dropdown

impact_dropdown: 
  label: Impacts
  dropdown_list: 
    -
      label: All
      value: All
    - 
      label: GWP
      value: Global Warming Potential Total (kgCO2eq)        
    - 
      label: AP
      value: Acidification Potential Total (kgSO2eq)
    - 
      label: EP
      value: Eutrophication Potential Total (kgNeq)
    - 
      label: ODP
      value: Ozone Depletion Potential Total (CFC-11eq)
    - 
      label: SFP
      value: Smog Formation Potential Total (kgO3eq)
  first_item: All
  dropdown_id: impact_dropdown

scope_dropdown_a4_scenario:
  label: Categorization
  dropdown_list:
    - 
      label: Revit Building Element
      value: Revit building element
    - 
      label: Tally Entry Division
      value: Tally Entry Division
    - 
      label: Revit Category
      value: Revit category
  first_item: Revit building element
  dropdown_id: scope_dropdown_a4_scenario

scope_dropdown_a5_scenario:
  label: Categorization
  dropdown_list:
    - 
      label: Revit Building Element
      value: Revit building element
    - 
      label: Tally Entry Division
      value: Tally Entry Division
    - 
      label: Revit Category
      value: Revit category
  first_item: Revit building element
  dropdown_id: scope_dropdown_a5_scenario

scope_dropdown_b4_scenario:
  label: Categorization
  dropdown_list:
    - 
      label: Revit Building Element
      value: Revit building element
    - 
      label: Tally Entry Division
      value: Tally Entry Division
    - 
      label: Revit Category
      value: Revit category
  first_item: Revit building element
  dropdown_id: scope_dropdown_b4_scenario

scope_dropdown_eol_scenario:
  label: Categorization
  dropdown_list:
    - 
      label: Revit Building Element
      value: Revit building element
    - 
      label: Tally Entry Division
      value: Tally Entry Division
    - 
      label: Revit Category
      value: Revit category
  first_item: Revit building element
  dropdown_id: scope_dropdown_eol_scenario

a4_scenario_radioitem: 
  label: Approach
  radiolist: 
    -
      label: Prebuilt Scenarios
      value: prebuilt
    - 
      label: Custom Scenarios
      value: custom 
  first_item: prebuilt
  radio_id: a4_scenario_radioitem


a4_scenario_checklist: 
  label: Transportation Scenarios
  checklist: 
    -
      label: Regional Supply Chain
      value: domestic_supply_chain
    - 
      label: Global Supply Chain
      value: global_supply_chain   
  first_item: []
  checklist_id: a4_scenario_checklist

a4_impact_dropdown: 
  label: Impacts
  dropdown_list: 
    - 
      label: GWP
      value: Global Warming Potential Total (kgCO2eq)        
    - 
      label: AP
      value: Acidification Potential Total (kgSO2eq)
    - 
      label: EP
      value: Eutrophication Potential Total (kgNeq)
    - 
      label: ODP
      value: Ozone Depletion Potential Total (CFC-11eq)
    - 
      label: SFP
      value: Smog Formation Potential Total (kgO3eq)
  first_item: Global Warming Potential Total (kgCO2eq)
  dropdown_id: a4_impact_dropdown

a5_scenario_radioitem: 
  label: Approach
  radiolist: 
    -
      label: Prebuilt Scenarios
      value: prebuilt
    - 
      label: Custom Scenarios
      value: custom 
  first_item: prebuilt
  radio_id: a5_scenario_radioitem

a5_scenario_checklist: 
  label: Construction Scenarios
  checklist: 
    - 
      label: All Electric Site Equipment
      value: 1_all_elec_equip
    - 
      label: Advanced Waste Recovery
      value: 2_waste_recovery
    - 
      label: Off-site Fabrication
      value: 3_off_site_fab
  first_item: []
  checklist_id: a5_scenario_checklist

a5_equipment_checklist:
  label: Equipment
  checklist: 
    -
      label: Site Heating
      value: site_heating
    - 
      label: Electric Lighting
      value: electric_lighting
    - 
      label: Grid Connection
      value: grid_connection
    - 
      label: Diesel Generators
      value: diesel_generatorss
  first_item: []
  checklist_id: a5_equipment_checklist


b4_scenario_radioitem: 
  label: Approach
  radiolist: 
    -
      label: Prebuilt Scenarios
      value: prebuilt
    - 
      label: Custom Scenarios
      value: custom 
  first_item: prebuilt
  radio_id: b4_scenario_radioitem

b4_scenario_checklist: 
  label: Replacement Scenarios
  checklist: 
    -
      label: RICS Replacement Rates
      value: RICS
    - 
      label: ASHRAE 240P Replacement Rates
      value: ASHRAE_240
  first_item: []
  checklist_id: b4_scenario_checklist

b4_impact_dropdown: 
  label: Impacts
  dropdown_list: 
    - 
      label: GWP
      value: Global Warming Potential Total (kgCO2eq)        
    - 
      label: AP
      value: Acidification Potential Total (kgSO2eq)
    - 
      label: EP
      value: Eutrophication Potential Total (kgNeq)
    - 
      label: ODP
      value: Ozone Depletion Potential Total (CFC-11eq)
    - 
      label: SFP
      value: Smog Formation Potential Total (kgO3eq)
  first_item: Global Warming Potential Total (kgCO2eq)
  dropdown_id: b4_impact_dropdown

eol_scenario_radioitem: 
  label: Approach
  radiolist: 
    -
      label: Prebuilt Scenarios
      value: prebuilt
    - 
      label: Custom Scenarios
      value: custom 
  first_item: prebuilt
  radio_id: eol_scenario_radioitem

eol_scenario_checklist: 
  label: End-of-life Scenarios
  checklist: 
    -
      label: Regional Mix
      value: regional_mix
  first_item: []
  checklist_id: eol_scenario_checklist

eol_impact_dropdown: 
  label: Impacts
  dropdown_list: 
    - 
      label: GWP
      value: Global Warming Potential Total (kgCO2eq)        
    - 
      label: AP
      value: Acidification Potential Total (kgSO2eq)
    - 
      label: EP
      value: Eutrophication Potential Total (kgNeq)
    - 
      label: ODP
      value: Ozone Depletion Potential Total (CFC-11eq)
    - 
      label: SFP
      value: Smog Formation Potential Total (kgO3eq)
  first_item: Global Warming Potential Total (kgCO2eq)
  dropdown_id: b4_impact_dropdown




