---
tm_dropdown:
  label: Template Model
  dropdown_list:
    - 
      label: Template Model 1
      value: tm_1
    - 
      label: Template Model 2
      value: tm_2_dummy
  first_item: tm_1
  dropdown_id: tm_dropdown

scope_dropdown:
  label: Categorization
  dropdown_list:
    - 
      label: Life Cycle Stage
      value: Life Cycle Stage
    - 
      label: Revit Building Element
      value: Revit building element
    - 
      label: Tally Entry Division
      value: Tally Entry Division
    - 
      label: Revit Category
      value: Revit category
  first_item: Life Cycle Stage
  dropdown_id: scope_dropdown

impact_dropdown: 
  label: Impacts
  dropdown_list: 
    -
      label: All
      value: All
    - 
      label: GWP
      value: Global Warming Potential Total (kgCO2eq)        
    - 
      label: AP
      value: Acidification Potential Total (kgSO2eq)
    - 
      label: EP
      value: Eutrophication Potential Total (kgNeq)
    - 
      label: ODP
      value: Ozone Depletion Potential Total (CFC-11eq)
    - 
      label: SFP
      value: Smog Formation Potential Total (kgO3eq)
  first_item: All
  dropdown_id: impact_dropdown

scope_dropdown_a4_scenario:
  label: Categorization
  dropdown_list:
    - 
      label: Life Cycle Stage
      value: Life Cycle Stage
    - 
      label: Revit Building Element
      value: Revit building element
    - 
      label: Tally Entry Division
      value: Tally Entry Division
    - 
      label: Revit Category
      value: Revit category
  first_item: Life Cycle Stage
  dropdown_id: scope_dropdown_a4_scenario

scope_dropdown_a5_scenario:
  label: Categorization
  dropdown_list:
    - 
      label: Life Cycle Stage
      value: Life Cycle Stage
    - 
      label: Revit Building Element
      value: Revit building element
    - 
      label: Tally Entry Division
      value: Tally Entry Division
    - 
      label: Revit Category
      value: Revit category
  first_item: Life Cycle Stage
  dropdown_id: scope_dropdown_a5_scenario

scope_dropdown_b4_scenario:
  label: Categorization
  dropdown_list:
    - 
      label: Life Cycle Stage
      value: Life Cycle Stage
    - 
      label: Revit Building Element
      value: Revit building element
    - 
      label: Tally Entry Division
      value: Tally Entry Division
    - 
      label: Revit Category
      value: Revit category
  first_item: Life Cycle Stage
  dropdown_id: scope_dropdown_b4_scenario

scope_dropdown_eol_scenario:
  label: Categorization
  dropdown_list:
    - 
      label: Life Cycle Stage
      value: Life Cycle Stage
    - 
      label: Revit Building Element
      value: Revit building element
    - 
      label: Tally Entry Division
      value: Tally Entry Division
    - 
      label: Revit Category
      value: Revit category
  first_item: Life Cycle Stage
  dropdown_id: scope_dropdown_eol_scenario

a4_scenario_radioitem: 
  label: Approach
  radiolist: 
    -
      label: Prebuilt Scenarios
      value: prebuilt
    - 
      label: Custom Scenarios
      value: custom 
  first_item: prebuilt
  radio_id: a4_scenario_radioitem


a4_scenario_checklist: 
  label: Transportation Scenarios
  checklist: 
    -
      label: Domestic Supply Chain
      value: 1_us_avg_dist
    - 
      label: Global Supply Chain
      value: 2_global_avg_dist    
    - 
      label: Electric Vehicles
      value: 3_elec_vehicles
  first_item: []
  checklist_id: a4_scenario_checklist

a5_scenario_radioitem: 
  label: Approach
  radiolist: 
    -
      label: Prebuilt Scenarios
      value: prebuilt
    - 
      label: Custom Scenarios
      value: custom 
  first_item: prebuilt
  radio_id: a5_scenario_radioitem

a5_scenario_checklist: 
  label: Construction Scenarios
  checklist: 
    - 
      label: All Electric Site Equipment
      value: 1_all_elec_equip
    - 
      label: Advanced Waste Recovery
      value: 2_waste_recovery
    - 
      label: Off-site Fabrication
      value: 3_off_site_fab
  first_item: []
  checklist_id: a5_scenario_checklist

a5_equipment_checklist:
  label: Equipment
  checklist: 
    -
      label: Site Heating
      value: site_heating
    - 
      label: Electric Lighting
      value: electric_lighting
    - 
      label: Grid Connection
      value: grid_connection
    - 
      label: Diesel Generators
      value: diesel_generatorss
  first_item: []
  checklist_id: a5_equipment_checklist


b4_scenario_radioitem: 
  label: Approach
  radiolist: 
    -
      label: Prebuilt Scenarios
      value: prebuilt
    - 
      label: Custom Scenarios
      value: custom 
  first_item: prebuilt
  radio_id: b4_scenario_radioitem

b4_scenario_checklist: 
  label: Replacement Scenarios
  checklist: 
    -
      label: RICS Replacement Rates
      value: 1_rics_repl_rates
    - 
      label: ASHRAE 240P Replacement Rates
      value: 2_ashrae_repl_rates
  first_item: []
  checklist_id: b4_scenario_checklist

eol_scenario_radioitem: 
  label: Approach
  radiolist: 
    -
      label: Prebuilt Scenarios
      value: prebuilt
    - 
      label: Custom Scenarios
      value: custom 
  first_item: prebuilt
  radio_id: eol_scenario_radioitem

eol_scenario_checklist: 
  label: End-of-life Scenarios
  checklist: 
    -
      label: Regional Mix
      value: 1_regional_mix
    - 
      label: 100% Landfill
      value: 2_100%_landfill    
    - 
      label: 100% Incineration
      value: 3_100%_incineration
    - 
      label: 100% Recycle / Reuse
      value: 4_100%_recycle
  first_item: []
  checklist_id: eol_scenario_checklist




