---
location_dropdown:
  label: Location
  dropdown_list:
    - 
      label: Los Angeles, CA
      value: Los Angeles, CA
    - 
      label: Philadelphia, PA
      value: Philadelphia, PA
      disabled: True
    - 
      label: Seattle, WA
      value: Seattle, WA
      disabled: True
    - 
      label: Chicago, IL
      value: Chicago, IL
      disabled: True
    - 
      label: Austin, TX
      value: Austin, TX
      disabled: True
    - 
      label: Atlanta, GA
      value: Atlanta, GA
      disabled: True
    - 
      label: Unknown
      value: Unknown
      disabled: True
  first_item: Philadelphia, PA
  dropdown_id: location_dropdown

building_use_type_dropdown:
  label: Building Use Type
  dropdown_list:
    - 
      label: Office
      value: Office
    - 
      label: Single family home
      value: Single Family Home
    - 
      label: Multi-family
      value: Multi-family
      disabled: True
    - 
      label: Education
      value: Education
      disabled: True
    - 
      label: Healthcare
      value: Healthcare
      disabled: True
  first_item: Office
  dropdown_id: building_use_type_dropdown

str_horiz_grav_sys_dropdown:
  label: Primary Horizontal Gravity System
  dropdown_list:
    - 
      label: "Concrete: non-PT framing"
      value: "Concrete: non-PT framing"
    - 
      label: "Steel: frame + concrete on metal deck"
      value: "Steel: Frame + concrete on metal deck"
    - 
      label: "Wood: engineered oanels"
      value: "Wood: engineered oanels"
  first_item: "Concrete: non-PT framing"
  dropdown_id: str_horiz_grav_sys_dropdown

str_vert_grav_sys_dropdown:
  label: Primary Vertical Gravity System
  dropdown_list:
    - 
      label: "Concrete: CIP"
      value: "Concrete: CIP"
    - 
      label: "Steel: columns"
      value: "Steel: columns"
    - 
      label: "Wood: mass timber"
      value: "Wood: mass timber"
  first_item: "Concrete: CIP"
  dropdown_id: str_vert_grav_sys_dropdown

str_lat_sys_dropdown:
  label: Primary Lateral System
  dropdown_list:
    - 
      label: "Concrete: shear walls"
      value: "Concrete: shear walls"
    - 
      label: "Steel: braced frames"
      value: "Steel: braced frames"
      disabled: True
    - 
      label: "Wood: shear panels"
      value: "Wood: shear panels"
      disabled: True
  first_item: "Concrete: shear walls"
  dropdown_id: str_lat_sys_dropdown

cladding_type_dropdown:
  label: Cladding Type
  dropdown_list:
    - 
      label: "Curtain wall: steel spandrel"
      value: "Curtain wall: steel spandrel"
    - 
      label: "Curtain wall: aluminum spandrel"
      value: "Curtain wall: aluminum spandrel"
    - 
      label: "MV: brick"
      value: "MV: brick"
    - 
      label: "MV: granite"
      value: "MV: granite"
    - 
      label: "Insulated metal panel"
      value: "Insulated metal panel"
    - 
      label: "EIFS (XPS)"
      value: "EIFS (XPS)"
    - 
      label: "Rainscreen: GFRC"
      value: "Rainscreen: GFRC"
    - 
      label: "Rainscreen: thin brick"
      value: "Rainscreen: thin brick"
    - 
      label: "Rainscreen: wood"
      value: "Rainscreen: wood"
    - 
      label: "Rainscreen: formed steel panel"
      value: "Rainscreen: formed steel panel"
  first_item: "Curtain wall: steel spandrel"
  dropdown_id: cladding_type_dropdown

roofing_type_dropdown:
  label: Roofing Type
  dropdown_list:
    - 
      label: "EPDM roofing"
      value: "EPDM roofing"
    - 
      label: "TPO roofing"
      value: "TPO roofing"
      disabled: True
    - 
      label: "Mod bit roofing"
      value: "Mod bit roofing"
      disabled: True
  first_item: "EPDM roofing"
  dropdown_id: roofing_type_dropdown

wwr_dropdown:
  label: Window-to-wall Ratio
  dropdown_list:
    - 
      label: "33%"
      value: "33%"
    - 
      label: "25%"
      value: "25%"
      disabled: True
    - 
      label: "50%"
      value: "50%"
      disabled: True
    - 
      label: "75%"
      value: "75%"
      disabled: True
  first_item: "33%"
  dropdown_id: wwr_dropdown

life_cycle_stage_dropdown:
  label: Life Cycle Stage
  dropdown_list:
    - 
      label: Transportation
      value: Transportation
    - 
      label: Construction
      value: Construction
    - 
      label: Replacement
      value: Replacement
    - 
      label: End-of-life
      value: End-of-life
  first_item: Transportation
  dropdown_id: life_cycle_stage_dropdown

scope_dropdown:
  label: Categorization
  dropdown_list:
    - 
      label: Revit building element
      value: Revit building element
    - 
      label: Tally entry division
      value: Tally Entry Division
    - 
      label: Revit category
      value: Revit category
  first_item: Revit building element
  dropdown_id: scope_dropdown

impact_dropdown: 
  label: Impacts
  dropdown_list: 
    - 
      label: GWP
      value: Global Warming Potential Total (kgCO2eq)        
    - 
      label: AP
      value: Acidification Potential Total (kgSO2eq)
    - 
      label: EP
      value: Eutrophication Potential Total (kgNeq)
    - 
      label: ODP
      value: Ozone Depletion Potential Total (CFC-11eq)
    - 
      label: SFP
      value: Smog Formation Potential Total (kgO3eq)
  first_item: Global Warming Potential Total (kgCO2eq)
  dropdown_id: impact_dropdown


transporation_scenario_checklist: 
  label: Prebuilt
  checklist: 
    -
      label: Regionally-specific Distances
      value: domestic_supply_chain
      disabled: True
    - 
      label: Global Supply Chain
      value: global_supply_chain
      disabled: True 
  first_item: []
  checklist_id: transporation_scenario_checklist

transporation_scenario_radio: 
  label: Prebuilt
  radiolist: 
    - 
      label: North American Average (default)
      value: default
    -
      label: Regionally-specific Distances
      value: domestic_supply_chain
      disabled: True
    - 
      label: Global Supply Chain
      value: global_supply_chain   
      disabled: True
  first_item: default
  radio_id: transporation_scenario_radio

construction_scenario_checklist: 
  label: Prebuilt
  checklist: 
    - 
      label: Advanced Waste Recovery
      value: Advanced Waste Recovery
      disabled: True
  first_item: []
  checklist_id: construction_scenario_checklist

construction_scenario_radio: 
  label: Prebuilt
  radiolist: 
    - 
      label: North American Average (default)
      value: default
    - 
      label: Advanced Waste Recovery
      value: Advanced Waste Recovery
      disabled: True
  first_item: default
  radio_id: construction_scenario_radio

replacement_scenario_checklist: 
  label: Prebuilt
  checklist: 
    -
      label: RICS Replacement Rates
      value: RICS
  first_item: [RICS]
  checklist_id: replacement_scenario_checklist'

replacement_scenario_radio: 
  label: Prebuilt
  radiolist: 
    - 
      label: ASHRAE 240P Replacement Rates (default)
      value: default
  first_item: default
  radio_id: replacement_scenario_radio

eol_scenario_checklist: 
  label: Prebuilt
  checklist: 
    -
      label: Regional C&D treatment mix 
      value: regional_mix
      disabled: True
  first_item: []
  checklist_id: eol_scenario_checklist

eol_scenario_radio: 
  label: Prebuilt
  radiolist: 
    - 
      label: National Ave C&D treatment mix (default)
      value: default
    -
      label: Regional C&D treatment mix
      value: regional_mix
      disabled: True
  first_item: default
  radio_id: eol_scenario_radio

category_orders:
  Transportation: 
    - default
    - domestic_supply_chain
    - global_supply_chain
  Construction: 
    - default
    - Advanced Waste Recovery
    - Off-site Fabrication
  Replacement: 
    - default
    - RICS
    - ASHRAE_240
  End-of-life: 
    - default
    - regional_mix

scope_dropdown_model_comp:
  label: Categorization
  dropdown_list:
    - 
      label: Life cycle stage
      value: Life cycle stage
    - 
      label: Revit building element
      value: Revit building element
    - 
      label: Tally entry division
      value: Tally Entry Division
    - 
      label: Revit category
      value: Revit category
  first_item: Revit building element
  dropdown_id: scope_dropdown_model_comp

impact_dropdown_model_comp: 
  label: Impacts
  dropdown_list: 
    - 
      label: GWP
      value: Global Warming Potential Total (kgCO2eq)        
    - 
      label: AP
      value: Acidification Potential Total (kgSO2eq)
    - 
      label: EP
      value: Eutrophication Potential Total (kgNeq)
    - 
      label: ODP
      value: Ozone Depletion Potential Total (CFC-11eq)
    - 
      label: SFP
      value: Smog Formation Potential Total (kgO3eq)
  first_item: Global Warming Potential Total (kgCO2eq)
  dropdown_id: impact_dropdown_model_comp


