---
location_dropdown:
  label: Location
  dropdown_list:
    - 
      label: Philadelphia, PA
      value: Philadelphia, PA
    - 
      label: Seattle, WA
      value: Seattle, WA
    - 
      label: Los Angeles, CA
      value: Los Angeles, CA
      disabled: True
    - 
      label: Chicago, IL
      value: Chicago, IL
      disabled: True
    - 
      label: Austin, TX
      value: Austin, TX
      disabled: True
    - 
      label: Atlanta, GA
      value: Atlanta, GA
      disabled: True
    - 
      label: Unknown
      value: Unknown
      disabled: True
  first_item: Philadelphia, PA
  dropdown_id: location_dropdown

building_use_type_dropdown:
  label: Building Use Type
  dropdown_list:
    - 
      label: Office
      value: Office
    - 
      label: Single Family Home
      value: Single Family Home
    - 
      label: Multi-family
      value: Multi-family
      disabled: True
    - 
      label: Education
      value: Education
      disabled: True
    - 
      label: Healthcare
      value: Healthcare
      disabled: True
  first_item: Office
  dropdown_id: building_use_type_dropdown

str_horiz_grav_sys_dropdown:
  label: Primary Horizontal Gravity System
  dropdown_list:
    - 
      label: "Concrete: Non-PT Framing"
      value: "Concrete: Non-PT Framing"
    - 
      label: "Steel: Frame + Concrete on Metal Deck"
      value: "Steel: Frame + Concrete on Metal Deck"
    - 
      label: "Wood: Engineered Panels"
      value: "Wood: Engineered Panels"
  first_item: "Concrete: Non-PT Framing"
  dropdown_id: str_horiz_grav_sys_dropdown

str_vert_grav_sys_dropdown:
  label: Primary Vertical Gravity System
  dropdown_list:
    - 
      label: "Concrete: CIP"
      value: "Concrete: CIP"
    - 
      label: "Steel: Columns"
      value: "Steel: Columns"
    - 
      label: "Wood: Mass Timber"
      value: "Wood: Mass Timber"
  first_item: "Wood: Mass Timber"
  dropdown_id: str_vert_grav_sys_dropdown

str_lat_sys_dropdown:
  label: Primary Lateral System
  dropdown_list:
    - 
      label: "Concrete: Shear Walls"
      value: "Concrete: Shear Walls"
    - 
      label: "Steel: Braced Frames"
      value: "Steel: Braced Frames"
    - 
      label: "Wood: Shear Panels"
      value: "Wood: Shear Panels"
      disabled: True
  first_item: "Concrete: Shear Walls"
  dropdown_id: str_lat_sys_dropdown

cladding_type_dropdown:
  label: Cladding Type
  dropdown_list:
    - 
      label: "Curtainwall"
      value: "Curtainwall"
    - 
      label: "Wood rainscreen"
      value: "Wood rainscreen"
  first_item: "Curtainwall"
  dropdown_id: cladding_type_dropdown

roofing_type_dropdown:
  label: Roofing Type
  dropdown_list:
    - 
      label: "Roof Option 1"
      value: "Roof Option 1"
    - 
      label: "Roof Option 2"
      value: "Roof Option 2"
  first_item: "Roof Option 1"
  dropdown_id: roofing_type_dropdown

wwr_dropdown:
  label: Window-to-wall Ratio
  dropdown_list:
    - 
      label: "25%"
      value: "25%"
    - 
      label: "50%"
      value: "50%"
    - 
      label: "75%"
      value: "75%"
  first_item: "75%"
  dropdown_id: wwr_dropdown

life_cycle_stage_dropdown:
  label: Life Cycle Stage
  dropdown_list:
    - 
      label: Transportation
      value: Transportation
    - 
      label: Construction
      value: Construction
    - 
      label: Replacement
      value: Replacement
    - 
      label: End-of-life
      value: End-of-life
  first_item: Transportation
  dropdown_id: life_cycle_stage_dropdown

scope_dropdown:
  label: Categorization
  dropdown_list:
    - 
      label: Revit Building Element
      value: Revit building element
    - 
      label: Tally Entry Division
      value: Tally Entry Division
    - 
      label: Revit Category
      value: Revit category
  first_item: Revit building element
  dropdown_id: scope_dropdown

impact_dropdown: 
  label: Impacts
  dropdown_list: 
    - 
      label: GWP
      value: Global Warming Potential Total (kgCO2eq)        
    - 
      label: AP
      value: Acidification Potential Total (kgSO2eq)
    - 
      label: EP
      value: Eutrophication Potential Total (kgNeq)
    - 
      label: ODP
      value: Ozone Depletion Potential Total (CFC-11eq)
    - 
      label: SFP
      value: Smog Formation Potential Total (kgO3eq)
  first_item: Global Warming Potential Total (kgCO2eq)
  dropdown_id: impact_dropdown


transporation_scenario_checklist: 
  label: Prebuilt Scenarios
  checklist: 
    -
      label: Regional Supply Chain
      value: domestic_supply_chain
    - 
      label: Global Supply Chain
      value: global_supply_chain   
  first_item: []
  checklist_id: transporation_scenario_checklist

transporation_scenario_radio: 
  label: Prebuilt Scenarios
  radiolist: 
    - 
      label: Default
      value: default
    -
      label: Regional Supply Chain
      value: domestic_supply_chain
    - 
      label: Global Supply Chain
      value: global_supply_chain   
  first_item: default
  radio_id: transporation_scenario_radio

construction_scenario_checklist: 
  label: Construction Scenarios
  checklist: 
    - 
      label: Advanced Waste Recovery
      value: Advanced Waste Recovery
    - 
      label: Off-site Fabrication
      value: Off-site Fabrication
  first_item: []
  checklist_id: construction_scenario_checklist

construction_scenario_radio: 
  label: Construction Scenarios
  radiolist: 
    - 
      label: Default
      value: default
    - 
      label: Advanced Waste Recovery
      value: Advanced Waste Recovery
    - 
      label: Off-site Fabrication
      value: Off-site Fabrication
  first_item: default
  radio_id: construction_scenario_radio

replacement_scenario_checklist: 
  label: Replacement Scenarios
  checklist: 
    -
      label: RICS Replacement Rates
      value: RICS
    - 
      label: ASHRAE 240P Replacement Rates
      value: ASHRAE_240
  first_item: []
  checklist_id: replacement_scenario_checklist'

replacement_scenario_radio: 
  label: Replacement Scenarios
  radiolist: 
    - 
      label: Default
      value: default
    -
      label: RICS Replacement Rates
      value: RICS
    - 
      label: ASHRAE 240P Replacement Rates
      value: ASHRAE_240
  first_item: default
  radio_id: replacement_scenario_radio

eol_scenario_checklist: 
  label: End-of-life Scenarios
  checklist: 
    -
      label: Regional Mix
      value: regional_mix
  first_item: []
  checklist_id: eol_scenario_checklist

eol_scenario_radio: 
  label: End-of-life Scenarios
  radiolist: 
    - 
      label: Default
      value: default
    -
      label: Regional Mix
      value: regional_mix
  first_item: default
  radio_id: eol_scenario_radio

category_orders:
  Transportation: 
    - default
    - domestic_supply_chain
    - global_supply_chain
  Construction: 
    - default
    - Advanced Waste Recovery
    - Off-site Fabrication
  Replacement: 
    - default
    - RICS
    - ASHRAE_240
  End-of-life: 
    - default
    - regional_mix

scope_dropdown_model_comp:
  label: Categorization
  dropdown_list:
    - 
      label: Life Cycle Stage
      value: Life Cycle Stage
    - 
      label: Revit Building Element
      value: Revit building element
    - 
      label: Tally Entry Division
      value: Tally Entry Division
    - 
      label: Revit Category
      value: Revit category
  first_item: Revit building element
  dropdown_id: scope_dropdown_model_comp

impact_dropdown_model_comp: 
  label: Impacts
  dropdown_list: 
    - 
      label: GWP
      value: Global Warming Potential Total (kgCO2eq)        
    - 
      label: AP
      value: Acidification Potential Total (kgSO2eq)
    - 
      label: EP
      value: Eutrophication Potential Total (kgNeq)
    - 
      label: ODP
      value: Ozone Depletion Potential Total (CFC-11eq)
    - 
      label: SFP
      value: Smog Formation Potential Total (kgO3eq)
  first_item: Global Warming Potential Total (kgCO2eq)
  dropdown_id: impact_dropdown_model_comp


